### ISSUE TITLE
Weird bug in Sphinx duplicate label handling

### ISSUE THREAD

**Issue by embray** [sagemath/sage-archive-2023-02-01#60]
(Putting bug report here for now until Trac is back up)

While building the docs I got this traceback:

```
[developer] /home/embray/src/sagemath/sage/src/doc/en/developer/coding_in_other.rst:160: WARNING: duplicate label section-gap, other instance in /home/embray/src/sagemath/sage/src/doc/en/developer/interfaces.rst
Error building the documentation.
Traceback (most recent call last):
  File "/home/embray/src/sagemath/sage/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/embray/src/sagemath/sage/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/embray/src/sagemath/sage/local/lib/python2.7/site-packages/sage_setup/docbuild/__main__.py", line 2, in <module>
    main()
  File "/home/embray/src/sagemath/sage/local/lib/python2.7/site-packages/sage_setup/docbuild/__init__.py", line 1637, in main
    builder()
  File "/home/embray/src/sagemath/sage/local/lib/python2.7/site-packages/sage_setup/docbuild/__init__.py", line 320, in _wrapper
    map_parallel(build_other_doc, L)
  File "/home/embray/src/sagemath/sage/local/lib/python2.7/site-packages/sage_setup/docbuild/__init__.py", line 142, in map_parallel
    return map(func, args)
  File "/home/embray/src/sagemath/sage/local/lib/python2.7/site-packages/sage_setup/docbuild/__init__.py", line 280, in build_other_doc
    getattr(get_builder(document), name)(*args, **kwds)
  File "/home/embray/src/sagemath/sage/local/lib/python2.7/site-packages/sage_setup/docbuild/__init__.py", line 103, in f
    runsphinx()
  File "/home/embray/src/sagemath/sage/local/lib/python2.7/site-packages/sage_setup/docbuild/sphinxbuild.py", line 215, in runsphinx
    raise exception
OSError: [developer] /home/embray/src/sagemath/sage/src/doc/en/developer/coding_in_other.rst:160: WARNING: duplicate label section-gap, other instance in /home/embray/src/sagemath/sage/src/doc/en/developer/interfaces.rst
```

Ok so there's a duplicate label, that's clear enough, and should be fixed.  The odd part is just 

```
other instance in /home/embray/src/sagemath/sage/src/doc/en/developer/interfaces.rst
```

But there is no `src/doc/env/developer/interfaces.rst`.  The file it seems to be referring to is in `src/doc/en/tutorials/`.  I haven't checked whether this is a Sage specific error or something general to Sphinx (looks like maybe the latter).  It's probably just a formatting error in the error message, but confusing all the same!

**Comment by fchapoton** [comment]
Is there a ticket for that now ? So that we can close this "issue"...

**Comment by embray** [comment]
Yes, I believe this was the same issue as https://trac.sagemath.org/ticket/21044
