### ISSUE TITLE
Sage Make error

### ISSUE THREAD

**Issue by woshibutian** [sagemath/sage-archive-2023-02-01#90]
When i install Sage from source code, i encountered the following problem. I guess the reason is that I have installed a python 3.6.5 using anaconda and there is a conflict when make Sage. But i'm not sure. How can i solve this problem? Does anyone face with this issue.

The following is the errors logged in the log file.

python -E ./setup.py  build
running build
running build_ext
Traceback (most recent call last):
  File "./setup.py", line 2402, in <module>
    main()
  File "./setup.py", line 2397, in main
    "Tools/scripts/2to3", "Tools/scripts/pyvenv"]
  File "/home/woshibutian/\udce4\udcb8\udc8b\udce8\udcbd\udcbd/sage-8.3/local/var/tmp/sage/build/python3-3.6.6/src/Lib/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/woshibutian/\udce4\udcb8\udc8b\udce8\udcbd\udcbd/sage-8.3/local/var/tmp/sage/build/python3-3.6.6/src/Lib/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/woshibutian/\udce4\udcb8\udc8b\udce8\udcbd\udcbd/sage-8.3/local/var/tmp/sage/build/python3-3.6.6/src/Lib/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/woshibutian/\udce4\udcb8\udc8b\udce8\udcbd\udcbd/sage-8.3/local/var/tmp/sage/build/python3-3.6.6/src/Lib/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/woshibutian/\udce4\udcb8\udc8b\udce8\udcbd\udcbd/sage-8.3/local/var/tmp/sage/build/python3-3.6.6/src/Lib/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/woshibutian/\udce4\udcb8\udc8b\udce8\udcbd\udcbd/sage-8.3/local/var/tmp/sage/build/python3-3.6.6/src/Lib/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/woshibutian/\udce4\udcb8\udc8b\udce8\udcbd\udcbd/sage-8.3/local/var/tmp/sage/build/python3-3.6.6/src/Lib/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "./setup.py", line 228, in build_extensions
    missing = self.detect_modules()
  File "./setup.py", line 764, in detect_modules
    for ln in fp:
  File "/home/woshibutian/\udce4\udcb8\udc8b\udce8\udcbd\udcbd/sage-8.3/local/var/tmp/sage/build/python3-3.6.6/src/Lib/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 74: ordinal not in range(128)
Makefile:597: recipe for target 'sharedmods' failed
make[4]: *** [sharedmods] Error 1
make[4]: Leaving directory '/home/woshibutian/下载/sage-8.3/local/var/tmp/sage/build/python3-3.6.6/src'
Error building Python.

real	1m49.177s
user	1m39.165s
sys	0m9.991s
************************************************************************
Error building package python3-3.6.6
************************************************************************
Please email sage-devel (http://groups.google.com/group/sage-devel)
explaining the problem and including the log file
  /home/woshibutian/下载/sage-8.3/logs/pkgs/python3-3.6.6.log
Describe your computer, operating system, etc.
If you want to try to fix the problem yourself, *don't* just cd to
/home/woshibutian/下载/sage-8.3/local/var/tmp/sage/build/python3-3.6.6 and type 'make' or whatever is appropriate.
Instead, the following commands setup all environment variables
correctly and load a subshell for you to debug the error:
  (cd '/home/woshibutian/下载/sage-8.3/local/var/tmp/sage/build/python3-3.6.6' && '/home/woshibutian/下载/sage-8.3/sage' --sh)
When you are done debugging, you can type "exit" to leave the subshell.

**Comment by slel** [comment]
Such support requests are best addressed to the [Ask Sage](https://ask.sagemath.org) questions-and-answers site,
or to the [sage-support](https://groups.google.com/forum/#!forum/sage-support) or [sage-devel](https://groups.google.com/forum/#!forum/sage-devel) mailing lists.

Hint: try removing Anaconda from your PATH.

If this does not solve the issue, ask on Ask Sage, sage-support or sage-devel,
following the instructions in the error message, in particular:

> Describe your computer, operating system, etc.
